- name: Use Jenkins pipeline parameters in Ansible
  hosts: localhost
  tasks:
    - name: Debug PARAM1 value
      debug:
        var: test

    - name: Debug PARAM2 value
      debug:
        var: email